### ISSUE TITLE
issues with LaMed-Phi3 inference

### ISSUE THREAD

**Issue by lzl199704** [BAAI-DCAI/M3D#33]
<img width="843" alt="Screenshot 2024-11-11 203559" src="https://github.com/user-attachments/assets/0eb59054-0ecf-4f0a-8713-08ca7a0bd4e2">
Cannot use the demo code for inference. 

Transformers==4.46.2
Torch==2.4.0

**Comment by baifanxxx** [comment]
Hi,

Thank you for your attention, please try a lower version of transformers.

**Comment by YongchengYAO** [comment]
transformers==4.45 works for me

**Comment by Coisini-Glenda** [comment]
This problem occurred during the eval_caption test：



RuntimeError: Error(s) in loading state_dict for Phi3ForCausalLM:
        size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([32015, 3072]) from checkpoint, the shape in current model is torch.Size([32064, 3072]).
        size mismatch for lm_head.weight: copying a param with shape torch.Size([32015, 3072]) from checkpoint, the shape in current model is torch.Size([32064, 3072]).

**Comment by zhouhoo** [comment]
> transformers==4.45 works for me

I got error as follow: `Token indices sequence length is longer than the specified maximum sequence length for this model (2963 > 512). Running this sequence through the model will result in indexing errors
  0%|                                                                                                                                                               | 0/64 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/root/M3D/Bench/eval/eval_vqa.py", line 162, in <module>
    main()
  File "/root/M3D/Bench/eval/eval_vqa.py", line 114, in main
    generation = model.generate(image, input_id, max_new_tokens=args.max_new_tokens,
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1804, in generate
    generation_config, model_kwargs = self._prepare_generation_config(generation_config, **kwargs)
  File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1355, in _prepare_generation_config
    model_kwargs = generation_config.update(**kwargs)
AttributeError: 'Tensor' object has no attribute 'update'`

it is version problem?

**Comment by heavy0ung** [comment]
> transformers==4.45 works for me

thanks for sharing your experience!

**Comment by Venn2336** [comment]
> > transformers==4.45 works for me
> 
> I got error as follow: `Token indices sequence length is longer than the specified maximum sequence length for this model (2963 > 512). Running this sequence through the model will result in indexing errors 0%| | 0/64 [00:02<?, ?it/s] Traceback (most recent call last): File "/root/M3D/Bench/eval/eval_vqa.py", line 162, in <module> main() File "/root/M3D/Bench/eval/eval_vqa.py", line 114, in main generation = model.generate(image, input_id, max_new_tokens=args.max_new_tokens, File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1804, in generate generation_config, model_kwargs = self._prepare_generation_config(generation_config, **kwargs) File "/root/miniconda3/envs/py310/lib/python3.10/site-packages/transformers/generation/utils.py", line 1355, in _prepare_generation_config model_kwargs = generation_config.update(**kwargs) AttributeError: 'Tensor' object has no attribute 'update'`
> 
> it is version problem?

I have the same problem too

**Comment by Khawaja-Murad** [comment]
> This problem occurred during the eval_caption test：
> 
> RuntimeError: Error(s) in loading state_dict for Phi3ForCausalLM: size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([32015, 3072]) from checkpoint, the shape in current model is torch.Size([32064, 3072]). size mismatch for lm_head.weight: copying a param with shape torch.Size([32015, 3072]) from checkpoint, the shape in current model is torch.Size([32064, 3072]).

did you manage to solve this error?
If yes , how?
